### ISSUE TITLE
UX: open issue details at the bottom of scroll

### ISSUE THREAD

**Issue by daveaglick** [spectresystems/ghostly-beta#13]
IMO the issue details pane should open at the bottom of the scroll instead of the top. For long issues, a new notification means there's new activity and that's presumably what we want to see. Right now you have to select the issue and then manually scroll to the bottom for each one. I'd rather it assume I want to look at the most recent stuff and make me scroll up when I need to.

**Comment by patriksvensson** [comment]
Would it make more sense of reversing the order the issues are shown (latest at the top?). Or should we add a button at the bottom to scroll to top?

**Comment by daveaglick** [comment]
> Would it make more sense of reversing the order the issues are shown (latest at the top?)

I assume you meant "reversing the order the comments are shown"? If so, that would be my first thought without any precedent, but I think there's value in keeping the issue details pane looking similar to the GitHub view of the issue. And that's descending with most recent at the bottom. Otherwise I suspect there will be a fair amount of cognitive dissonance switching between the two.

> Or should we add a button at the bottom to scroll to top?

That sounds like a good compromise - open the details pane scrolled to the bottom but provide a simple "Scroll To Top" button if you really wanted the top.

Maybe even better (though more work) would be to show the very first comment that opens the issue for context and then the bottom of the comment scroll. Getting the UI right for that could be tricky, but it could be pretty nice to open an issue and see the initial comment to remind me what I'm looking at with the new comments right off the bat. There's also the problem of showing the project name and other metadata when initially opening an issue that's scroll to the bottom. Maybe something like a floating block that only appears when you're at the bottom and disappears if you scroll?

![2019-01-18_12h11_06](https://user-images.githubusercontent.com/1020407/51402220-dfd6b280-1b1a-11e9-92ce-e88be4beb1b4.png)

Or maybe always show the project name and first comment in a pane above the other comments with a splitter and collapser, regardless of scroll position.

Or maybe show a single scrollable pane with the project name and first comment at top, a "Click to expand all" link or button for all the intermediate comments, and the most recent comment(s) at the bottom.

**Comment by patriksvensson** [comment]
Great ideas and food for thought!
