### ISSUE TITLE
Ghostly requests permissions which are not explained

### ISSUE THREAD

**Issue by hansmbakker** [spectresystems/ghostly-beta#15]
Ghostly requests a lot of permissions during authorization.

Especially the write access to all public and private repositories is not clear if it is necessary and why it is necessary - since Ghostly is about fetching notifications.

Why does Ghostly need to push code or need to read deploy keys?

Please keep the required permissions minimal.

![image](https://user-images.githubusercontent.com/3463496/52273403-07ff4780-294a-11e9-9b1b-41762c289ee1.png)

**Comment by patriksvensson** [comment]
@hansmbakker 

Sadly, GitHub permissions are not very fine grained and does not distinguish between read and write permissions for all scopes. The permissions we need to be able to read private repository information (issues/pull requests/releases and security vulnerabilities), notifications and user information are:

* `read:user`
* `repo`
* `notifications`

Which you can read about here: https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/#available-scopes

So if we want to be able to get notifications regarding private repositories there's really nothing we can do about this.

One option would be to have a "public mode" as well which only gets notifications and similar from public repositories, in that case we would only need the `read:user` and `notifications` scopes.

**Comment by patriksvensson** [comment]
@hansmbakker Actually, I think we can remove the `read:user` scope after having re-read the documentation for the scopes since we don't need any private information about the user, just the ability to call the "current user api" to get the username.

**Comment by patriksvensson** [comment]
@hansmbakker I've added an option to only watch public repositories (which only requires the `notifications` permission scope). Will be available in the next version

![image](https://user-images.githubusercontent.com/357872/52345237-f5097780-2a1c-11e9-903c-044490422491.png)

**Comment by hansmbakker** [comment]
Nice! I understand this might be a limitation of GitHub, but it was just a bit surprising to see GitHub ask for write permissions to code without a warning upfront.

Would the `notifications` scope instead of the `repo` be an option?

**Comment by patriksvensson** [comment]
@hansmbakker Yes, just asking for `notifications` scope is what "Public repositories only" does in the image above.

If we want to be able to get information about work items (issues/prs etc) that are private, we need the `repo` in addition to the `notifications` scope (which is what the second option in the image does).

**Comment by patriksvensson** [comment]
So public repositories only = `notifications`
Public and private repositories = `notifications`, `repo`

**Comment by patriksvensson** [comment]
@hansmbakker There is a new version released (0.1.24000.0) which will add an option to only request the `notifications` scope.
