### ISSUE TITLE
Feature Request: Untriaged Issues

### ISSUE THREAD

**Issue by RichiCoder1** [spectresystems/ghostly-beta#20]
An optional view that allows you to view untriaged issues for a repo. Maybe configurable be either being unlabelled or (if you have a bot) has a specific label like `Untriaged`.

**Comment by patriksvensson** [comment]
Should be possible by adding a filter view.

![image](https://user-images.githubusercontent.com/357872/62006469-0bc59700-b141-11e9-91dc-5165383cc81b.png)
