### ISSUE TITLE
Feature Request: Clicking on a notification for an archived issue doesn't work

### ISSUE THREAD

**Issue by RichiCoder1** [spectresystems/ghostly-beta#24]
I got a notification for an issue, but when I clicked on it the Window came to the forefront but otherwise it was just the issue view. I didn't realize it was an archived issue notification until I glanced at the header.

Clicking on a notification for an issue you take you to the appropriate tab and select the appropriate issue.

**Comment by patriksvensson** [comment]
Actually not a bug since it never worked this way, but it absolutely should. Changing this to a feature request! 😄
