### ISSUE TITLE
Bug: Tooltip is showing on content area

### ISSUE THREAD

**Issue by punker76** [spectresystems/ghostly-beta#28]
The Tooltips are sometimes showing on the content area on the different tabs.

![2019-02-06_21h58_34](https://user-images.githubusercontent.com/658431/52505911-3fd9e980-2bed-11e9-9dfc-47603a9e78cd.png)

![2019-02-06_22h00_30](https://user-images.githubusercontent.com/658431/52505956-5da74e80-2bed-11e9-9dd0-ef32946d420e.png)

![2019-02-08_22h03_19](https://user-images.githubusercontent.com/658431/52505953-5aac5e00-2bed-11e9-9401-5bcde12f9079.png)

**Comment by patriksvensson** [comment]
@punker76 Yeah, I've noticed this as well. Seems to be a problem with UWP apps and shortcuts for some reason. Will investigate if there's an workaround for this. Thanks for reporting 👍

**Comment by patriksvensson** [comment]
Fixed. Will be resolved in 0.2.6.
