### ISSUE TITLE
Make it possible to run in background

### ISSUE THREAD

**Issue by hansmbakker** [spectresystems/ghostly-beta#29]
I would like to run Ghostly in the ~system tray~ background so that it is not in my way until there is a notification. I can then decide to open the app.

**Comment by patriksvensson** [comment]
Currently this is not possible since it's an UWP application. I could ship an companion application that's not UWP with Ghostly, but that requires additional permissions for the package. I need to look into this and think about it.

**Comment by hansmbakker** [comment]
Yes I can imagine, still from a functional perspective it would be a nice to have.

Maybe another option is to have a background task (without system tray icon) that checks for updates periodically even when the app is closed? I believe this is possible with UWP.

**Comment by patriksvensson** [comment]
@hansmbakker I've started working on this 😄
