### ISSUE TITLE
Feature request: project grouping

### ISSUE THREAD

**Issue by daveaglick** [spectresystems/ghostly-beta#3]
I watch a lot of projects and seeing all the notifications together gets a little daunting. Being able to group and/or filter them by project would make managing them much easier.

**Comment by patriksvensson** [comment]
This can be accomplished by either creating a filter category, or simply crafting a search query (if you don't want to have filters). In version 0.4.0 you will also be able to add rules for incoming notifications.

![image](https://user-images.githubusercontent.com/357872/62006489-5e06b800-b141-11e9-90d1-109202f8dbdc.png)
