### ISSUE TITLE
Bug: Navigation menu items hard to see in dark mode

### ISSUE THREAD

**Issue by punker76** [spectresystems/ghostly-beta#30]
The Navigation menu items are not visible in dark mode of the OS until hovering.

**Windows specifications**
Windows 10 Enterprise
1903
18362.175

![2019-06-18_21h20_58](https://user-images.githubusercontent.com/658431/59713239-356cd380-920f-11e9-8a20-d6841b3dcbbf.png)

**Comment by patriksvensson** [comment]
@punker76 Good catch! I'm working on a proper dark mode, so theme related fixes will be fixed when that is in place. Thanks for reporting, much appreciated! 👍
