### ISSUE TITLE
Feature request: show project in the details pane

### ISSUE THREAD

**Issue by daveaglick** [spectresystems/ghostly-beta#7]
It's easy to loose track of which project the issue you're looking at is in when quickly going through them

![2019-01-18_08h06_07](https://user-images.githubusercontent.com/1020407/51388685-2e268a00-1af8-11e9-97f8-0682d4959942.png)

**Comment by patriksvensson** [comment]
Something like this?

![image](https://user-images.githubusercontent.com/357872/51397521-b54c2000-1b41-11e9-8d91-c4ba94a1420e.png)

**Comment by daveaglick** [comment]
Yes! That's perfect - I like how the light gray for the project name and issue number naturally associate to each other.

**Comment by patriksvensson** [comment]
Implemented. Will appear in v0.1.8.
